// <auto-generated />
namespace Engefibra.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class RelatoriosObra : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RelatoriosObra));
        
        string IMigrationMetadata.Id
        {
            get { return "201510281326439_Relatorios-Obra"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
